export const METIERS = [
  "Aromathérapeute",
  "Astrologue",
  "Cartomancienne",
  "Coach bien-être",
  "Coach yoga",
  "Energéticien",
  "Hypnothérapeute",
  "Magnétiseur",
  "Médium",
  "Naturopathe",
  "Ostéopathe",
  "Praticien massage",
  "Psychologue",
  "Réflexologue",
  "Reiki",
  "Sophrologue",
  "Autre praticien",
]
